// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0rpgAbRylVibv6BxnYm5hbAoTjr5-PFE',
    appId: '1:462078938105:web:cf6c514a56d66bb24f0b28',
    messagingSenderId: '462078938105',
    projectId: 'lotogroup-1ea8a',
    authDomain: 'lotogroup-1ea8a.firebaseapp.com',
    storageBucket: 'lotogroup-1ea8a.appspot.com',
    measurementId: 'G-ZR7FLRHFTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPu2R1yA7OZzrtUJxCrmWiEsPMp7JJFLk',
    appId: '1:462078938105:android:1a84a81fb9e2dd094f0b28',
    messagingSenderId: '462078938105',
    projectId: 'lotogroup-1ea8a',
    storageBucket: 'lotogroup-1ea8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAB2bVNgyvr9np3HDZCadpE4xYEf_FlFE',
    appId: '1:462078938105:ios:b8f619d84b968e9d4f0b28',
    messagingSenderId: '462078938105',
    projectId: 'lotogroup-1ea8a',
    storageBucket: 'lotogroup-1ea8a.appspot.com',
    iosBundleId: 'com.enescerrahoglu.templateAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAB2bVNgyvr9np3HDZCadpE4xYEf_FlFE',
    appId: '1:462078938105:ios:b8f619d84b968e9d4f0b28',
    messagingSenderId: '462078938105',
    projectId: 'lotogroup-1ea8a',
    storageBucket: 'lotogroup-1ea8a.appspot.com',
    iosBundleId: 'com.enescerrahoglu.templateAppBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0rpgAbRylVibv6BxnYm5hbAoTjr5-PFE',
    appId: '1:462078938105:web:9182944e598e68f74f0b28',
    messagingSenderId: '462078938105',
    projectId: 'lotogroup-1ea8a',
    authDomain: 'lotogroup-1ea8a.firebaseapp.com',
    storageBucket: 'lotogroup-1ea8a.appspot.com',
    measurementId: 'G-JF2NQ28YYD',
  );
}
